### ISSUE TITLE
Terra service does not authenticate on startup

### ISSUE THREAD

**Issue by mtmorgan** [Bioconductor/AnVIL#2]
From BJ on slack

> I created a token with gcloud tools (I am not sure if googleAuthR can do this as well), then copied the file to auth.json in the terra service folder. I modified the json to add the "installed" bit at the top and reinstalled. The authenticate("terra") now works. But, I cannot use the terra api with the token. I think it is because when the terra service is built, the token does not exist. I can use the token with httr and an api endpoint.
> I think we may want to give users the option to rebuild the service to pick the token used. This seems to work
> library(AnVIL)
> library(rapiclient)
> myf=system.file(package="AnVIL","service/terra/api.json")
> myToken=authenticate("terra")
> 
> b=get_api(myf, config=httr::config(token=myToken))
> b$schemes <- "https"
> b$host <- "api.firecloud.org"
> myapi=operations <- get_operations(b)

**Comment by bjstubbs** [comment]
Firecloud token generation

I do not have a service account linked to firecloud, so I generated a generic google cloud email based token.

0. Set up an account at firecloud 
1. Install  gcloud tools https://cloud.google.com/sdk/docs/quickstarts
2. Generate a token with gcloud auth login myemail@myemail.com
3. Copy the file ~/.config/gcloud/legacy_credentials/myemail@email.com/adc.json to AnVIL/inst/service/terra/auth.json
4. Edit auth.json to add {"installed": to the top and } to the bottom
5. Reinstall AnVIL

This should let you authenticate to firecloud

**Comment by bjstubbs** [comment]
Workflow adapted from here:
https://github.com/broadinstitute/firecloud-tools/blob/master/auth.sh

**Comment by mtmorgan** [comment]
With the version of commit c2da7d8, and without step 4 above (no longer needed) I get

```
> terra$getEntityTypes(namespace, workspace) %>% str()

List of 6
 $ statusCode: int 404
 $ source    : chr "rawls"
 $ timestamp : num 1.55e+12
 $ causes    : list()
 $ stackTrace: list()
 $ message   : chr "fccredits-indium-azure-9792/TCGA_LUSC_hg38_OpenAccess_GDCDR-12-0_DATA_copy does not exist"
```
I'm not sure whether that's another step I need to do, or other problem. Also I'm not sure whether step 2 generates a time-limited token?

Note some handy commands `flatten()` (for tibble, e.g., `leondard$listClusters() %>% flatten()`) and `str()` to extract responses; maybe there are more...

**Comment by bjstubbs** [comment]
That is most likely because you don't have access to my workspace. I will install the new version and test.

**Comment by bjstubbs** [comment]
Both Leonardo and Terra apis are working. Thanks!

**Comment by LiNk-NY** [comment]
Should this be closed?
