### ISSUE TITLE
AnVIL package series

### ISSUE THREAD

**Issue by LiNk-NY** [Bioconductor/AnVIL#20]
@mtmorgan @nturaga 
Should we be creating a suite of packages for use on Terra? 

It seems like this package could be divided into two (possibly three): 
1) Exposing the various APIs
2) Enabling GCloud functionality through R
3) Authentication (?)

cc: @vjcitn

**Comment by mtmorgan** [comment]
I don't like the 'suite' idea. It failed w/ biocLite(). I think the problem is that there is no suite, but rather a forest of paths through the woods...

**Comment by mtmorgan** [comment]
Where there might be bears...
