### ISSUE TITLE
Bioconductor submission

### ISSUE THREAD

**Issue by LiNk-NY** [Bioconductor/AnVIL#22]
Are there any plans to make this package part of Bioconductor? 

I have a couple of packages that make use of the `AnVIL::Service` class: 

https://github.com/waldronlab/cBioPortalData
https://github.com/Bioconductor/HCAMatrixBrowser

**Comment by mtmorgan** [comment]
yes during this release cycle

**Comment by LiNk-NY** [comment]
Hi all, @mtmorgan @nturaga 
Is there anything I can do to move this along?
I would like to also send the above packages in after this one. Thanks!
