### ISSUE TITLE
api.yaml and api_reference_url

### ISSUE THREAD

**Issue by LiNk-NY** [Bioconductor/AnVIL#23]
Hi Martin, @mtmorgan 
Is there a reason for having both the `inst/services/serviceX/api.yaml` file when there is an `api_reference_url` set?
I thought that a hard-coded md5sum should be enough to replace the need for an `api.yaml` file. Am I approaching this wrong? Thanks.

Context: 

When using `api_reference_url` only: 
```r
        Service(
            service = "cBioPortal",
            host = "www.cbioportal.org",
            config = httr::config(ssl_verifypeer = 0L, ssl_verifyhost = 0L,
                http_version = 0L),
            authenticate = FALSE,
            api_reference_url = "https://www.cbioportal.org/api/api-docs",
            api_reference_md5sum = "1f171b7c612ee6589945ba74dd5ba8c6",
            package = "cBioPortalData",
            schemes = "http"
        )
```
I get an error: 

```r
Error in .api_path(service, package) : 
  could not find api.json or api.yaml for service 'cBioPortal'
```
indicating that an `api.yaml` file is required because `api_url` is empty: 

https://github.com/Bioconductor/AnVIL/blob/e2b283e1786c2b48a35df67745c03f54d106db74/R/Service.R#L151-L156

Should it be the following? :  

```r
if (length(api_reference_url))
    path <- api_reference_url
```

**Comment by LiNk-NY** [comment]
I can go ahead and create a PR with this change, Martin @mtmorgan

**Comment by mtmorgan** [comment]
The Leonardo use case is that `inst/services/Leonardo/api.yaml` is a modified version of the reference, and the modifications need to be consistent with the reference. So we track the reference independently of the service.
