### ISSUE TITLE
possible glitch in delocalize with symlinks?

### ISSUE THREAD

**Issue by vjcitn** [Bioconductor/AnVIL#24]
it will take some time to make a reprex but maybe this will trigger a thought ... i will try cp -r

![deloc](https://user-images.githubusercontent.com/4624066/89688068-6a366100-d8cf-11ea-8171-44323dbb05d0.png)

**Comment by mtmorgan** [comment]
I think this is reflecting gsutil command line behavior

```
> gsutil_help("rsync")
...
  -e             Exclude symlinks. When specified, symbolic links will be
                 ignored. Note that gsutil does not follow directory symlinks,
                 regardless of whether -e is specified.
```
The rationale is described here https://github.com/GoogleCloudPlatform/gsutil/issues/412#issuecomment-286185229 and I don't think we should implement a workaround for this...
