### ISSUE TITLE
2 params with the same name for `terra$overwriteWorkspaceMethodConfig`

### ISSUE THREAD

**Issue by shbrief** [Bioconductor/AnVIL#28]
I'm trying to use `terra$overwriteWorkspaceMethodConfig` and got this error
```
Error in terra$overwriteWorkspaceMethodConfig(workspaceNamespace = input$workspaceNamespace,  : 
  argument 2 matches multiple formal arguments
```
and found that there are 2 parameters with the same name, `workspaceName`.
```
Parameters:
  workspaceNamespace (string)
    Workspace Namespace
  workspaceName (string)
    Workspace Name
  configNamespace (string)
    Configuration Namespace
  configName (string)
    Configuration Name
  inputs (object)
    Map[String, String] with inputs information
  methodRepoMethod (object)
    Map[String, String] with corresponding method-related information
  name (string)
    Method configuration name
  namespace (string)
    Method configuration namespace
  outputs (object)
    Map[String, String] with outputs information
  prerequisites (object)
    Map[String, String] of prerequisites (keys unused, will be removed in the future)
  rootEntityType (string)
    Root entity type
  workspaceName (object)
    Map[String, String] with corresponding workspace-related information - name and namespace
```

Can someone help me to resolve this? Thanks!

**Comment by LiNk-NY** [comment]
@mtmorgan @shbrief 

It looks like `rapiclient` combines both argument lists from `terra$overwriteWorkspaceMethodConfig` and `schemas(terra)$ConfigurationIngest` where the `workspaceName` name is used in both.
Same with `terra$updateWorkspaceMethodConfig` etc.

A simple way to fix this is to rename the second `workspaceName` to `workspacename` in the `ConfigurationIngest` spec in the `inst/service/terra/api.yaml` file.

**Comment by mtmorgan** [comment]
The second set of arguments are supposed to be in the body, not the argument.

**Comment by LiNk-NY** [comment]
So it looks like `get_message_body(op_def, x)` should return this information.
