### ISSUE TITLE
Dockstore API Bearer Token Authentication

### ISSUE THREAD

**Issue by bjstubbs** [Bioconductor/AnVIL#3]
I am not sure where we want to address this in the code, but to authenticate against the dockstore api, you need to include your bearer token in every request.

https://dockstore.org/accounts shows you your token. This can be saved to the dockstore auth file like the others. It is just a string.

Then, what we need to do is add this to the get_operations() call for dockstore as a header like

(assuming my token is stored in a variable called myb)

get_operations(dockstore,.headers=c(Authorization=paste("Bearer",myb))

There is a also an extra "api" in the url path. I removed one from the service call. 

I have a possible fix in my fork, but I am not sure if you want to go the route I did. 

https://github.com/bjstubbs/AnVIL/commit/c07b4823fa8f9b22d60ea9d9e3303da7a5c7ab3d

**Comment by nturaga** [comment]
Hi @bjstubbs,

I'll keep track of this since I added the dockstore service to the package.
