### ISSUE TITLE
AnVIL issue when accessing data table - random NA value found

### ISSUE THREAD

**Issue by figueroakl** [Bioconductor/AnVIL#32]
Terra notebook that has been used for several datasets is now adding an 'NA' value when reading in file names.

**Comment by mtmorgan** [comment]
Can you provide an example that I can reproduce? Can you verify that the corresponding row in the AnVIL table actually _does_ have a file name?, for instance, if the value were 'missing' in the data set, it would be replaced by NA when representing the data as a 'tibble'.

**Comment by mtmorgan** [comment]
I can't help to address this without a reproducible example, so will close.
