### ISSUE TITLE
does AnVIL::install refrain from reinstalling installed packages?

### ISSUE THREAD

**Issue by vjcitn** [Bioconductor/AnVIL#40]

**Comment by vjcitn** [comment]
My sense is that it does not.  So I tried BiocManager::install with repos=AnVIL::repositories() but that is not allowed.  So I set options(repos=AnVIL::repositories()) and I am not sure that gets me binary installations when available, within the community Rstudio environment on AnVIL.

**Comment by mtmorgan** [comment]
Yes, the current version of AnVIL does this. Following from the example in https://github.com/Bioconductor/AnVIL/issues/41

```
> AnVIL::install("Bioconductor/AnVIL")
'getOption("repos")' replaces Bioconductor standard repositories, see
'?repositories' for details

replacement repositories:
    CRAN: https://packagemanager.rstudio.com/all/__linux__/focal/latest

Bioconductor version 3.14 (BiocManager 1.30.16), R 4.1.1 (2021-08-10)
Installing github package(s) 'Bioconductor/AnVIL'
Skipping install of 'AnVIL' from a github remote, the SHA1 (19962a69) has not changed since last install.
  Use `force = TRUE` to force installation
...
```

See also `AnVIL::repository()` (singular) for just the binary repository.
