### ISSUE TITLE
can AnVIL::install handle x/y argument, indicating an installation from github?

### ISSUE THREAD

**Issue by vjcitn** [Bioconductor/AnVIL#41]

**Comment by mtmorgan** [comment]
In Bioconductor release 3.14, `AnVIL::install()` can do anything `BiocManager::install()` can do, except support a custom `site_repository=` (the `site_repository=` argument is used to specify the binary package location).

```
$ docker run -it --rm bioconductor/bioconductor_docker:RELEASE_3_14 R --quiet
> packageVersion("AnVIL")
[1] ‘1.6.0’
> AnVIL::install("Bioconductor/AnVIL")
...
> packageVersion("AnVIL")
[1] ‘1.7.0’
