### ISSUE TITLE
can't check reference_url without auth token

### ISSUE THREAD

**Issue by LiNk-NY** [Bioconductor/AnVIL#42]
The Service class attempts to check the api URL and validate against the stored md5 sum. 
When a token is required to access the URL, it fails. 

```r
> cBioPortal("genie.cbioportal.org", token = "xxx")
Error in download.file(reference_url, fl, quiet = TRUE) : 
  cannot open URL 'https://genie.cbioportal.org/api/api-docs'
In addition: Warning message:
In download.file(reference_url, fl, quiet = TRUE) :
  cannot open URL 'https://genie.cbioportal.org/api/api-docs': HTTP status was '
401 Unauthorized'
```

Min. reprex: 

``` r
tryCatch({
    AnVIL:::.service_validate_md5sum(
        "https://genie.cbioportal.org/api/api-docs",
        'md5sum_example'
    )
}, error = function(e) {
    conditionMessage(e)
})
#> Warning in download.file(reference_url, fl, quiet = TRUE): cannot open URL
#> 'https://genie.cbioportal.org/api/api-docs': HTTP status was '401 Unauthorized'
#> [1] "cannot open URL 'https://genie.cbioportal.org/api/api-docs'"
```

<sup>Created on 2021-11-12 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

The function should be extended to use tokens already provided as in `Terra()`. 

To sign up to genie: https://genie.cbioportal.org/login.jsp

**Comment by mtmorgan** [comment]
Can you clarify how I would download this file 'by hand'? What do I want to do with that token?

**Comment by LiNk-NY** [comment]
You could obtain it by doing: 

```r
> library(httr)
> GET("https://genie.cbioportal.org/api/api-docs",
+     add_headers(Authorization = paste("Bearer", token))
+ )
Response [https://genie.cbioportal.org/api/api-docs]
  Date: 2021-11-12 22:59
  Status: 200
  Content-Type: application/json
  Size: 86.7 kB
```

With the token we want to read the `api-docs` URL and also use the api services.

**Comment by inodb** [comment]
@mtmorgan to add - the API token is used to authenticate against instances of cBioPortal that require authentication. The example above authenticates against the GENIE instance of cBioPortal, which requires users to log in

Note that anyone can sign up for the GENIE instance: https://genie.cbioportal.org/login.jsp. It's mainly a way to make sure people agree to the data use terms

Once signed up one can download the token manually by clicking at the top right side of the page. See also: https://docs.cbioportal.org/2.2-authorization-and-authentication/authenticating-users-via-tokens#using-data-access-tokens

Hope that helps clarify the use case! Thanks for the prompt reply

**Comment by mtmorgan** [comment]
The branch https://github.com/Bioconductor/AnVIL/tree/Service_api_header allows a header to be passed to `AnVIL:::.service_validate_md5sum()` via the `Service(api_reference_headers =)` argument.

I can appreciate the notion that endpoints require authentication; is it a little unusual for the API specification itself to require authentication?

I guess other functionality will need (optional?) authentication. The following changes might provide hints -- storing the header in the cBioPortal class, and providing it to `operations()`.

```
cBioPortalData master$ git diff
diff --git a/R/cBioPortal.R b/R/cBioPortal.R
index bf1dcd8..db64baf 100644
--- a/R/cBioPortal.R
+++ b/R/cBioPortal.R
@@ -25,7 +25,11 @@ utils::globalVariables(c("clinicalAttributeId", "value", "sampleId"))
 #' cBioPortal()
 #'
 #' @export
-.cBioPortal <- setClass("cBioPortal", contains = "Service")
+.cBioPortal <- setClass(
+    "cBioPortal",
+    contains = "Service",
+    slots = c(api_header = "character")
+)

 #' @rdname cBioPortal
 #'
@@ -133,9 +137,11 @@ utils::globalVariables(c("clinicalAttributeId", "value", "sampleId"))
 #'
 #' @export
 cBioPortal <- function(
-    hostname = "www.cbioportal.org", protocol = "https", api. = "/api/api-docs"
+    hostname = "www.cbioportal.org", protocol = "https", api. = "/api/api-docs",
+    token = NULL
 ) {
     apiUrl <- paste0(protocol, "://", hostname, api.)
+    api_header = c(Authorization= paste("Bearer", token))
     .cBioPortal(
         Service(
             service = "cBioPortal",
@@ -146,12 +152,27 @@ cBioPortal <- function(
             authenticate = FALSE,
             api_reference_url = apiUrl,
             api_reference_md5sum = "6abc321feb60da3251620743b527bab9",
+            api_reference_headers = api_header,
             package = "cBioPortalData",
             schemes = protocol
-        )
+        ),
+        api_header = api_header
     )
 }

+.api_header <- function(x) x@api_header
+
+#' @importFrom AnVIL operations
+#' @export
+setMethod(
+    "operations", "cBioPortal",
+    function(x, ..., .deprecated = FALSE)
+{
+    callNextMethod(
+        x, .headers = .api_header(x), ..., .deprecated = .deprecated
+    )
+})
+
 .loadReportData <- function() {
     denv <- new.env(parent = emptyenv())
     api_file <- system.file(
(END)
```

Please let me know if this addresses the issue.

**Comment by LiNk-NY** [comment]
Thanks Martin! 
Sorry I forgot to mention that I created a branch to get optional authentication working here: 
https://github.com/waldronlab/cBioPortalData/compare/master..token
I will test this out.

**Comment by LiNk-NY** [comment]
Hi Martin, @mtmorgan 

Can this be merged to the master branch? 
Some folks at cBioPortal would like to use the functionality. 

See here https://github.com/waldronlab/cBioPortalData/issues/17

Best,
Marcel
