### ISSUE TITLE
`repository_stats` should report the resolved resource link and Bioc version

### ISSUE THREAD

**Issue by LiNk-NY** [Bioconductor/AnVIL#47]
I can help with this, if needed.

**Comment by mtmorgan** [comment]
Thanks @LiNk-NY  for the offer.

I started a branch https://github.com/Bioconductor/AnVIL/tree/repository_stats_enhancements for this. Bioconductor version is easy; I think the container identifier code needs to be factored out & reused from `repository()` and a pull request would be great.

I changed the output of `repostory_stats()` to a named list of class 'repostory_stats', and implemented a print.repository_stats method, so the output can be computed on (e.g., logged). I think print.repository_stats has to be exported to be visible, so then it makes sense to export repository_stats() also, documenting both on the same man page.

A pull request would be great!

**Comment by LiNk-NY** [comment]
Hi Martin, @mtmorgan 

What did you have in mind for the `container` input? 
We don't really have a name for these containers on Terra, except for when `platform == "terra-jupyter-r"`. 
It would be good to report the `binary_repository` variable as well. 

-MR

**Comment by mtmorgan** [comment]
the endpoint will be `packages/<bioc-version>/container-binaries/<container>/...` with container == `bioconductor_docker` or `terra-jupyter-r`
