### ISSUE TITLE
[branch: gadgets] .workspace_server should be adaptible

### ISSUE THREAD

**Issue by LiNk-NY** [Bioconductor/AnVIL#57]
Thanks Martin! 
The gadgets look neat!

I have a set of filtered workspaces (meant to work with terraTCGAdata) that I would like the user to see when running `AnVIL::workspace()`, e.g., 

```r
terraTCGAdata::findTCGAworkspaces()
```

```r
testthat::with_mock(`AnVIL:::.workspaces` = terraTCGAdata::findTCGAworkspaces, workspace())
```
It would be convenient to be able to provide some mechanism for either filtering or providing the tibble that is shown in the gadget. 
I can work on a PR if you'd like. 
Best,
Marcel

**Comment by mtmorgan** [comment]
What do you think of the (exported) `.gadget_run()` function? The man page has
```
tibble <- avworkspaces()
DONE_FUN <- function(tibble, row_selected) {
    selected <- slice(tibble, row_selected)
    with(selected, paste0(namespace, "/", name))
}
.gadget_run("AnVIL Example", tibble, DONE_FUN)
```
to illustrate how one could customize / reuse the 'table selection' gadget.

**Comment by LiNk-NY** [comment]
Hi Martin, @mtmorgan 
Thanks for adding this feature!
I have just implemented it in [terraTCGAdata@gadgets](https://github.com/waldronlab/terraTCGAdata/tree/gadgets)

**Comment by LiNk-NY** [comment]
Hi Martin, @mtmorgan 
Any updates on this? Should it be merged to the devel branch?

**Comment by LiNk-NY** [comment]
Hi Martin, @mtmorgan 
Can this be merged https://github.com/Bioconductor/AnVIL/tree/gadgets?
I'd be happy to help with this. 
Best,
Marcel
