### ISSUE TITLE
`avworkflow_stop` is 'aborting' again?

### ISSUE THREAD

**Issue by shbrief** [Bioconductor/AnVIL#64]
Hi Martin,

It seems like `avworkflow_stop` is 'aborting' the submissions that are successfully completed or aborted already. Can we make this function not run on submissions with the following status: 'Done', 'Aborted', and 'Aborting'?

Sehyun

**Comment by mtmorgan** [comment]
This might be tested with

```
BiocManager::install("Bioconductor/AnVIL", ref = "stop-running-workflows-only", force = TRUE)
```

**Comment by shbrief** [comment]
Working as desired now - it's not changing the finalized status (i.e. `Done` and `Aborted`) anymore. Thanks!!
