### ISSUE TITLE
Create a new bucket

### ISSUE THREAD

**Issue by shbrief** [Bioconductor/AnVIL#72]
Is there an AnVIL function for creating a new bucket? (equivalent to `gsutil mb`)

**Comment by mtmorgan** [comment]
No; one might use `gsutil_lm`, for instance, as a template to implement this.

**Comment by shbrief** [comment]
Thanks for the clarification. I might implement that functionality. 
Btw, is `gsutil_lm` an existing function? What does it stand for? I can't find it;;

**Comment by mtmorgan** [comment]
sorry, I meant `gsutil_ls`...
