### ISSUE TITLE
unexpected type conversion by avtable_import

### ISSUE THREAD

**Issue by smgogarten** [Bioconductor/AnVIL#77]
avtable_import of a character string that might be interpreted as containing scientific notation is automatically converted to a number:

```
> t <- tibble(file_id="0098817a", analysis_id="7291533d")
> avtable_import(t)
pageSize = 1 rows (1 pages)
# A tibble: 1 × 5
   page from_row to_row job_id                               status  
  <int>    <int>  <int> <chr>                                <chr>   
1     1        1      1 713eece7-d0df-4ec4-a775-7b58e7c423aa Uploaded
> avtable("file")
# A tibble: 1 × 2
  file_id  analysis_id
  <chr>          <int>
1 0098817a     7291533
```

**Comment by smgogarten** [comment]
<img width="611" alt="Screen Shot 2023-05-23 at 3 31 05 PM" src="https://github.com/Bioconductor/AnVIL/assets/2028958/de0f8480-3a37-497c-993f-e48ec924a229">

**Comment by mtmorgan** [comment]
Thank you for the report. This seems to be a problem with the Terra table import functionality (I can reproduce the problem by writing to a TSV file `write.table(t, "file.tsv", sep = "\t", quote = FALSE, row.names = FALSE)` (or `quote = TRUE`) and then using the GUI to IMPORT TABLE.

I contacted Terra support about this and will let you know what I hear back.

**Comment by mtmorgan** [comment]
Terra support says

> Thanks for bringing this to our attention. I was able to reproduce the issue on my end so I've filed a bug report for our engineers to look into.
>
> We'll be sure to reach back out when the bug is resolved.

**Comment by mtmorgan** [comment]
Terra support responded yesterday

> Just wanted to follow up here and let you know that our engineers have released a fix for this bug.

and it seems to be fixed
```
t <- tibble(file_id="0098817a", analysis_id="7291533d")
status <- avtable_import(t)
avtable("file")
## # A tibble: 1 × 2
##   file_id  analysis_id
##   <chr>    <chr>      
## 1 0098817a 7291533d   
```
