### ISSUE TITLE
Need to run `avworkflow_configuration_set()` before `avworkflow_run()` if updating configuration inputs

### ISSUE THREAD

**Issue by amstilp** [Bioconductor/AnVIL#84]
First, thanks for putting together such a useful package! I really do appreciate the functionality it provides.

That said, I've encountered another issue when submitting workflows. In this case, it looks like the documentation in the [vignette](https://bioconductor.org/packages/release/bioc/vignettes/AnVIL/inst/doc/RunningWorkflow.html) and the behavior on AnVIL is different. I've made an example workspace on AnVIL with two Rmd files documenting the difference and can share it with the Bioconductor team if it's helpful.

The issue happens when I am trying to update workflow configuration inputs compared to what's already saved in AnVIL, and run the workflow using that new configuration. The documentation says to update the config object, and that it should run the workflow with the updated configuration parameters. The code essentially boils down to:
```
new_config <- avworkflow_config_update(config, inputs)
avworkflow_run(new_config, NULL, dry=FALSE)
```
(I've passed `NULL` for `entityName` since I am operating on files in the workspace instead of over records in a data table.)

The main difference I've found is that I need to run `avworkflow_configuration_set()` after updating the config and before submitting the workflow with `avworkflow_run()`:
```
new_config <- avworkflow_config_update(config, inputs)
avworkflow_configuration_set(new_config, dry=FALSE)
avworkflow_run(new_config, NULL, dry=FALSE)
```

In my example workspace, I've checked two different things:

1. Starting with a workflow that I've just imported and has no saved inputs yet, I get an error submitting a workflow unless I run `avworkflow_configuration_set()` with the `new_config`.
2. If a workflow has a saved configuration, that configuration is used instead of the configuration specified in `new_config` even when I call `avworkflow_run(new_config, NULL, dry=FALSE)`.

I'm not sure if this is
1. an issue with AnVIL/Terra APIs not working with a configuration that's different than what's already saved in AnVIL
2. an issue with the `AnVIL` Bioconductor package, where it doesn't pass the `new_config` contents to the API call for submitting a workflow job, or 
3. just a documentation update in section 4.1 to make it clear that you need to run `avworkflow_configuration_set()` to update config parameters before calling `avworkflow_run()`.

If case 3, it them seems like the new_config argument to `avworkflow_run` is unnecessary, since it is using the saved configuration. Furthermore, `avworkflow_configuration_set()` is described later in the vignette (section 4.2), but it doesn't say that it's necessary for running a workflow with config parameters that are different than what is currently saved for the workflow.

Again -- happy to share my example workspace. Just let me know who to share it with.

**Comment by amstilp** [comment]
Digging into this a little: it looks like the underlying API call to [createSubmission](https://rawls.dsde-prod.broadinstitute.org/#/submissions/createSubmission) does not allow you to pass different inputs, so I'm guessing it defaults to using the inputs that are saved in the current workflow configuration.

I think the fix here is just to modify the vignette and roxygen documentation to state that if you are changing inputs to a workflow, you need to set the workspace configuration with `avworkflow_configuration_set()` before calling `avworkflow_run()`.

**Comment by mtmorgan** [comment]
Thanks @amstilp I'll try to update this by the middle of the week.

**Comment by amstilp** [comment]
Thanks! It might be helpful to document somewhere which info from the `config` object is used when submitting the workflow (eg, `rootEntityType`, `name` and `namespace`? based on [the code](https://github.com/Bioconductor/AnVIL/blob/devel/R/avworkflow.R#L594)), and which info is pulled from AnVIL (eg, the inputs).

**Comment by mtmorgan** [comment]
Please let me know if the documentation changes https://github.com/Bioconductor/AnVIL/pull/85/files do the trick; of course feel free to further revise!

Also wanted to mention [AnVILWorkflow](https://bioconductor.org/packages/AnVILWorkflow) in case it is of interest -- I think the goal was to make things more 'user friendly'.

**Comment by amstilp** [comment]
The changes look great, thanks! I hadn't heard of `AnVILWorkflow` but I'll look into it for the future.
